Repository Groupify-SCE/groupify-frontend, pull requests merged in 2025-03, with the labels that each got.

#10 Feature/profile details
  src/pages/Profile.page.js
  src/services/user.service.js
  src/styles/ProfilePage.style.css
Labels: enhancement

#11 Feature/project button
  src/App.js
  src/components/Navbar.js
  src/pages/Profile.page.js
  src/styles/Alert.style.css
  src/styles/AuthPage.style.css
  src/styles/Navbar.style.css
  src/styles/ProfilePage.style.css
Labels: enhancement

#12 Sprint 3
  .eslintrc.js
  .github/workflows/cicd.yml
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/fonts/DMSans/DMSans-Bold.ttf
  src/assets/fonts/DMSans/DMSans-BoldItalic.ttf
  src/assets/fonts/DMSans/DMSans-Italic.ttf
  src/assets/fonts/DMSans/DMSans-Medium.ttf
  src/assets/fonts/DMSans/DMSans-MediumItalic.ttf
  src/assets/fonts/DMSans/DMSans-Regular.ttf
  src/assets/images/groupify-logo.png
  src/components/DarkModeToggle.js
  src/components/Navbar.js
  src/index.css
  src/logo.svg
  src/pages/ForgotPassword.page.js
  src/pages/Landing.page.js
  src/pages/Login.page.js
  src/pages/Profile.page.js
  src/pages/ResetPassword.page.js
  src/pages/Signup.page.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
  src/styles/Alert.style.css
  src/styles/AuthPage.style.css
  src/styles/DarkModeToggle.style.css
  src/styles/Navbar.style.css
  src/styles/ProfilePage.style.css
Labels: devops

#13 Stage
  .eslintrc.js
  .github/workflows/cicd.yml
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/fonts/DMSans/DMSans-Bold.ttf
  src/assets/fonts/DMSans/DMSans-BoldItalic.ttf
  src/assets/fonts/DMSans/DMSans-Italic.ttf
  src/assets/fonts/DMSans/DMSans-Medium.ttf
  src/assets/fonts/DMSans/DMSans-MediumItalic.ttf
  src/assets/fonts/DMSans/DMSans-Regular.ttf
  src/assets/images/groupify-logo.png
  src/components/DarkModeToggle.js
  src/components/Navbar.js
  src/index.css
  src/index.js
  src/pages/ForgotPassword.page.js
  src/pages/Landing.page.js
  src/pages/Login.page.js
  src/pages/Profile.page.js
  src/pages/ResetPassword.page.js
  src/pages/Signup.page.js
  src/reportWebVitals.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
  src/setupTests.js
  src/styles/Alert.style.css
  src/styles/AuthPage.style.css
  src/styles/DarkModeToggle.style.css
  src/styles/Navbar.style.css
  src/styles/ProfilePage.style.css
Labels: bug

#14 Hotfix
  src/App.js
  src/App.test.js
  src/styles/Navbar.style.css
Labels: bug

#15 V0.3.0
  .eslintrc.js
  .github/workflows/cicd.yml
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/App.test.js
  src/assets/fonts/DMSans/DMSans-Bold.ttf
  src/assets/fonts/DMSans/DMSans-BoldItalic.ttf
  src/assets/fonts/DMSans/DMSans-Italic.ttf
  src/assets/fonts/DMSans/DMSans-Medium.ttf
  src/assets/fonts/DMSans/DMSans-MediumItalic.ttf
  src/assets/fonts/DMSans/DMSans-Regular.ttf
  src/assets/images/groupify-logo.png
  src/components/DarkModeToggle.js
  src/components/Navbar.js
  src/index.css
  src/logo.svg
  src/pages/ForgotPassword.page.js
  src/pages/Landing.page.js
  src/pages/Login.page.js
  src/pages/Profile.page.js
  src/pages/ResetPassword.page.js
  src/pages/Signup.page.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
  src/styles/Alert.style.css
  src/styles/AuthPage.style.css
  src/styles/DarkModeToggle.style.css
  src/styles/Navbar.style.css
  src/styles/ProfilePage.style.css
Labels: devops

#16 Feature/add env url
  package-lock.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/App.test.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
Labels: bug

#17 Fixed cookies
  package-lock.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
Labels: bug

#18 Sprint 3: fixed cookies bug in production
  package-lock.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
Labels: devops

#20 Dev
  package-lock.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/App.test.js
  src/services/auth.service.js
  src/services/backend.manager.js
  src/services/user.service.js
  src/styles/Navbar.style.css
Labels: enhancement

#22 Feature/creat project
  src/pages/Project.page.js
  src/services/project.service.js
  src/styles/ProjectPage.style.css
Labels: enhancement

#24 Feature/delete project
  src/components/ConfirmDeletion.js
  src/pages/Project.page.js
  src/services/project.service.js
Labels: enhancement

#27 fixed input checking
  src/pages/ProjectManagement.page.js
Labels: enhancement

#28 Feature/UI design
  src/styles/ProjectManagementPage.style.css
  src/styles/ProjectPage.style.css
Labels: enhancement

#29 Finished sprint 4
  src/App.js
  src/components/ConfirmDeletion.js
  src/pages/Profile.page.js
  src/pages/Project.page.js
  src/pages/ProjectManagement.page.js
  src/services/project.service.js
  src/styles/ProjectManagementPage.style.css
  src/styles/ProjectPage.style.css
Labels: devops

#30 Finished Version 0.4.0
  src/App.js
  src/components/ConfirmDeletion.js
  src/pages/Profile.page.js
  src/pages/Project.page.js
  src/pages/ProjectManagement.page.js
  src/services/project.service.js
  src/styles/ProjectManagementPage.style.css
  src/styles/ProjectPage.style.css
Labels: devops

#32 Feature/add participants
  package-lock.json
  package.json
  src/App.css
  src/components/AddParticipantForm.js
  src/contexts/Participants.section.js
  src/pages/ProjectManagement.page.js
  src/services/project.service.js
  src/styles/ParticipantsSection.style.css
Labels: enhancement

#33 added get all participants implemention
  src/contexts/Participants.section.js
  src/services/project.service.js
Labels: enhancement
